name: CI Pipeline

on:
    push:
        branches:
            - main
    workflow_dispatch:
jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        
        steps:
            - name: Write config file
              run: |
                echo "{ 
                "mybigsecret": "Hello World!"
                }" > src/config.json
